language: generic
before_install:
  - sudo add-apt-repository ppa:fontforge/fontforge -y
  - sudo apt-get update -qq
  - sudo apt-get install fontforge
install:
  - make
notifications:
  webhooks: http://webhook.hakatashi.com/travis
